name: Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        haxe-version: [4.2.5, 4.3.3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cedx/setup-hashlink@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install utest --quiet
          haxelib install hxcpp --quiet
          haxelib git haxeparser https://github.com/HaxeCheckstyle/haxeparser.git aaba9287c53af55b253b2d1069582731ffa5f93f --quiet
          haxelib git mxhx-resolver https://github.com/mxhx-dev/mxhx-resolver.git --quiet
          haxelib dev mxhx-source-resolver ${{ github.workspace }}
      - name: Run Interpreter Tests
        working-directory: test
        run: haxe test.hxml --interp
      - name: Run Neko Tests
        working-directory: test
        run: |
          haxe test.hxml --neko bin/test.n
          neko bin/test.n
      - name: Run HashLink Tests
        working-directory: test
        run: |
          haxe test.hxml --hl bin/test.hl
          hl bin/test.hl
      - name: Run C++ Tests
        working-directory: test
        run: |
          haxe test.hxml --cpp bin/test
          bin/test/Main
